name: "Publish CML dockers"

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  TEST_GITHUB_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }} 
  TEST_GITHUB_REPO: https://github.com/iterative/cml_qa_tests_dummy
  TEST_GITHUB_SHA: 62edc8b3f46a60b3fe1e5c08fd3e0046d350ee29
  TEST_GITLAB_TOKEN: ${{ secrets.TEST_GITLAB_TOKEN }}
  TEST_GITLAB_REPO: https://gitlab.com/iterative.ai/cml_qa_tests_dummy
  TEST_GITLAB_SHA: c4c13286e78dc252dd2611f31a755f10d343fbd4
  TEST_BBCLOUD_TOKEN: ${{ secrets.TEST_BBCLOUD_TOKEN }}
  TEST_BBCLOUD_REPO:  https://bitbucket.org/iterative-ai/cml-qa-tests-dummy
  TEST_BBCLOUD_SHA: 8119698b09994844a6803d5380cc370e0d0ffc6a

jobs:
  test_and_deploy:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: "npm ci"
      run: npm ci

    - name: "lint"
      run: npm run lint

    - name: "tests"
      run: |
        sudo update-alternatives --install /usr/bin/python python $(which python3) 10
        sudo apt-get update && sudo apt-get install -y python3-pip 
        sudo pip install --upgrade pip
        sudo pip install --upgrade setuptools
        sudo pip install tensorboard

        npm run test

    - name: Publish CML docker image
      # only publish if push to master (dvcorg/cml:latest) 
      # or create a tag in the repo (dvcorg/cml:tag)
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: dvcorg/cml
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: ./docker/Dockerfile
        context: ./
        cache: true
        tag_names: true

    - name: Publish cml-py3 docker image
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      uses: elgohr/Publish-Docker-Github-Action@v5
      env:
        DOCKER_FROM: cml
      with:
        name: dvcorg/cml-py3
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: ./docker/Dockerfile-py3
        context: ./
        cache: true
        tag_names: true
        buildargs: DOCKER_FROM

    - name: Publish cml-dev docker image
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: dvcorg/cml-dev
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        dockerfile: ./docker/Dockerfile-dev
        context: ./
        cache: true
        tag_names: true

    # cloud-runner aliases will be deprecated
    - name: Alias cloud-runner
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      run: | 
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
         
        docker tag dvcorg/cml dvcorg/cml-gpu && docker push dvcorg/cml-gpu
        docker tag dvcorg/cml-py3 dvcorg/cml-gpu-py3 && docker push dvcorg/cml-gpu-py3
        
        docker tag dvcorg/cml dvcorg/cml-cloud-runner && docker push dvcorg/cml-cloud-runner
        docker tag dvcorg/cml-py3 dvcorg/cml-py3-cloud-runner && docker push dvcorg/cml-py3-cloud-runner
        docker tag dvcorg/cml-gpu dvcorg/cml-gpu-cloud-runner && docker push dvcorg/cml-gpu-cloud-runner
        docker tag dvcorg/cml-gpu-py3 dvcorg/cml-gpu-py3-cloud-runner && docker push dvcorg/cml-gpu-py3-cloud-runner

    - name: Publish to NPM
      if: github.event_name == 'push' && (contains(github.ref, 'tags') || github.ref == 'refs/heads/master')
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        npm publish
      env:
        NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
